spring:
  application:
    name: 'food-delivery_customer'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
server:
  port: 8083

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: customer
    password: customer
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  profiles: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}