services:

  bff:
    container_name: bff
    build:
      context: .
      dockerfile: Dockerfile
      args:
        app_name: bff
    environment:
      - SPRING_REDIS_HOST=redis
    ports:
      - 8081:8080
    depends_on:
      - redis

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
      - 8181:8001
    volumes:
      - redis-data:/data

volumes:
  redis-data: