services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infra/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=food_delivery
      - POSTGRES_USER=food_delivery
      - POSTGRES_PASSWORD=food_delivery

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
      - 8181:8001
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  postgres-data: