services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infra/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=food_delivery
      - POSTGRES_USER=food_delivery
      - POSTGRES_PASSWORD=food_delivery

  redis:
    image: redis:7-alpine
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  redis-insight:
    image: redislabs/redisinsight:1.12.1
    container_name: redis-insight
    ports:
      - 8181:8001
    depends_on:
      - redis
    volumes:
      - ./infra/redisinsight:/db

volumes:
  redis-data:
  postgres-data: