management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: 'food-delivery_ordering'
  datasource:
    driver-class-name: io.wkrzywiec.fooddelivery.infra.repository.JsonbPostgreSQLDialect
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true