FROM gradle:8.7.0-jdk21 as build
WORKDIR /app
COPY ./ ./
RUN gradle clean assemble --info


FROM eclipse-temurin:21-jre-alpine as main
ARG app_name
WORKDIR /app
COPY --from=build /app/$app_name/build/libs/$app_name-0.0.1-SNAPSHOT.jar ./app.jar
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=prod"]




