spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: 'farm-to-table_food'
  profiles:
    default: prod
    group:
      dev:
        - redis
      prod:
        - redis

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

---
server:
  port: 8084

spring:
  profiles: dev

---

spring:
  profiles: redis
  redis:
    host: localhost
    port: 6379
