spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: 'farm-to-table_food'
  profiles:
    default: prod
    group:
      dev:
        - redis
      prod:
        - redis

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

---
server:
  port: 8084

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
