spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: 'food-delivery_food'

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
server:
  port: 8084

spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  config:
    activate:
      on-profile: prod
