spring:
  application:
    name: 'food-delivery_ordering'

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
server:
  port: 8082

spring:
  profiles: dev

---
spring:
  profiles: prod