spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: 'food-delivery_food'

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
server:
  port: 8084

spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
---
spring:
  profiles: prod