spring:
  application:
    name: 'farm-to-table_ordering'
  profiles:
    default: prod
    group:
      dev:
        - redis-stream
        - dev-local
      prod:
        - redis-stream
      redis:
        - redis-inbox
        - redis-stream
        - dev-local

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
server:
  port: 8082

spring:
  profiles: dev

---
spring:
  profiles: prod