management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: 'food-delivery_customer'
  datasource:
    driver-class-name: org.hibernate.dialect.PostgreSQL10Dialect
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true