spring:
  application:
    name: 'farm-to-table_delivery'
  profiles:
    default: prod
    group:
      dev:
        - redis-stream
        - redis-event-store
        - dev-local
      prod:
        - redis-stream
        - redis-event-store
      redis:
        - redis-event-store
        - redis-stream
  liquibase:
    enabled: false
    change-log: db/changelog/changelog-master.xml
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
server:
  port: 8083

spring:
  profiles: dev

---
spring:
  profiles: prod