spring:
  application:
    name: 'food-delivery_delivery'

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
server:
  port: 8083

spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod