spring:
  application:
    name: 'farm-to-table_delivery'

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
server:
  port: 8083

spring:
  profiles: dev

---
spring:
  profiles: prod