spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: 'food-delivery_bff'

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod