spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: 'farm-to-table_bff'

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
server:
  port: 8081

spring:
  profiles: dev

---
spring:
  profiles: prod