spring:
  application:
    name: 'farm-to-table_bff'
  profiles:
    default: prod
    group:
      dev:
        - postgres-inbox
        - redis-stream
        - dev-local
      prod:
        - postgres-inbox
        - redis-stream
      redis:
        - redis-inbox
        - redis-stream
        - dev-local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    enabled: false
    change-log: db/changelog/changelog-master.xml
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# todo is it needed?
server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

---

spring:
  config:
    activate:
      on-profile: postgres-inbox
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:bff}
    username: ${POSTGRES_USERNAME:bff}
    password: ${POSTGRES_PASSWORD:bff}
  liquibase:
    enabled: true

---

spring:
  config:
    activate:
      on-profile: dev-local

server:
  port: 8081

logging:
  level:
    io.wkrzywiec.fooddelivery: info

---

