management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: 'food-delivery-app'
  datasource:
    url: jdbc:tc:postgresql:9.6.8:///food_delivery
    username: food_delivery
    password: food_delivery
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true