name: Test - feature branch
on:
  push:
    branches-ignore:
      - 'main'
  workflow_dispatch:

jobs:
  bff:
    uses: ./.github/workflows/templates/gradle-project-branch.yaml
    with:
      app-name: bff
      
  delivery:
    uses: ./.github/workflows/templates/gradle-project-branch.yaml
    with:
      app-name: delivery