name: Test - feature branch
on:
  push:
    branches-ignore:
      - 'main'
  workflow_dispatch:

jobs:
  bff:
    uses: ./.github/workflows/template-gradle-project-branch.yaml
    with:
      app-name: bff
      
  delivery:
    uses: ./.github/workflows/template-gradle-project-branch.yaml
    with:
      app-name: delivery
      
  food:
    uses: ./.github/workflows/template-gradle-project-branch.yaml
    with:
      app-name: food
      
  ordering:
    uses: ./.github/workflows/template-gradle-project-branch.yaml
    with:
      app-name: ordering