name: Test - feature branch
on:
  push:
    branches-ignore:
      - 'main'
  workflow_dispatch:

jobs:
  qa:
    uses: wkrzywiec/gh-workflows/.github/workflows/java-gradle-branch.yaml@main
    with:
      app-name: food-delivery