name: Build
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
#  bff:
#    uses: ./.github/workflows/template-gradle-project-main.yaml
#    with:
#      app-name: bff
#  
#  delivery:
#    uses: ./.github/workflows/template-gradle-project-main.yaml
#    with:
#      app-name: delivery
#  
#  food:
#    uses: ./.github/workflows/template-gradle-project-main.yaml
#    with:
#      app-name: food
#  
#  ordering:
#    uses: ./.github/workflows/template-gradle-project-main.yaml
#    with:
#      app-name: ordering


  security:
    name: Security scan
    runs-on: ubuntu-latest
#    needs: [bff, delivery, food, ordering]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Gradlew permissions
        working-directory: services
        run: |
          chmod +x ./gradlew

      - name: Run Snyk & upload to results to the cloud
        uses: snyk/actions/gradle-jdk17@master
        env:
          SNYK_TOKEN: ${{ secrets.snykToken }}
        with:
          command: monitor --file services/build.gradle

      - name: Run Snyk to check for vulnerabilities 👮‍♀️
        uses: snyk/actions/gradle-jdk17@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.snykToken }}
        with:
          args: --severity-threshold=high --sarif-file-output=snyk.sarif --file services/build.gradle

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

#  sonar:
#    runs-on: ubuntu-latest
#    needs: [bff, delivery, food, ordering]
#    steps:
#
#      - uses: actions/checkout@v3
#
#      - uses: actions/download-artifact@v3
#        with:
#          name: bff-code-coverage
#          path: ./services/bff/build/reports/jacoco/test/jacocoTestReport.xml
#
#      - uses: actions/download-artifact@v3
#        with:
#          name: delivery-code-coverage
#          path: ./services/delivery/build/reports/jacoco/test/jacocoTestReport.xml
#
#      - uses: actions/download-artifact@v3
#        with:
#          name: food-code-coverage
#          path: ./services/food/build/reports/jacoco/test/jacocoTestReport.xml
#
#      - uses: actions/download-artifact@v3
#        with:
#          name: ordering-code-coverage
#          path: ./services/ordering/build/reports/jacoco/test/jacocoTestReport.xml
#
#      - name: Set permissions for gradlew
#        working-directory: services
#        run: |
#          chmod +x ./gradlew
#
#      - name: Sonar Cloud 🌟
#        working-directory: services
#        run: |
#          ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.verbose=true --info
#        env:
#          GITHUB_TOKEN: ${{ secrets.githubToken }}
#          SONAR_TOKEN: ${{ secrets.sonarToken }}
