name: Build
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  qa:
    uses: wkrzywiec/gh-workflows/.github/workflows/java-gradle.yaml@main
    with:
      app-name: food-delivery
      path: services
    secrets:
      sonarToken: ${{ secrets.SONAR_TOKEN }}
      githubToken: ${{ secrets.GITHUB_TOKEN }}